stages:
  - build
  - test
  - deploy

before_script:
  - echo "Initialisation du stage $CI_JOB_STAGE"
  - mvn --version

after_script:
  - echo "Nettoyage du stage $CI_JOB_STAGE terminé"

job_build:
  stage: build
  tags:
    - pc-younes
  script:
    - mvn clean compile

job_test:
  stage: test
  tags:
    - pc-younes
  script:
    - mvn test
  allow_failure: true 

job_deploy:
  stage: deploy
  tags:
    - pc-younes
  script:
    - echo "Younes : Génération du WAR et déploiement local..."
    - mvn package -DskipTests
    - mkdir -p ~/deploy_inpt_java/
    - cp target/*.war ~/deploy_inpt_java/
    - echo "Déploiement terminé dans ~/deploy_inpt_java/"
  only:
    - main
    - master