stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  tags:
    - pc-younes
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

job_test:
  stage: test
  tags:
    - pc-younes
  script:
    - mvn test
  # On autorise la suite si les tests passent
  dependencies:
    - job_build

job_deploy_to_aws:
  stage: deploy
  tags:
    - pc-younes
  script:
    - echo "Connexion à l'IP -> $AWS_IP"
    - mvn package -DskipTests
    - chmod 400 "$AWS_PRIVATE_KEY"
    # On utilise *.jar ici !
    - scp -o StrictHostKeyChecking=no -i "$AWS_PRIVATE_KEY" target/*.jar ubuntu@$AWS_IP:/tmp/
    - ssh -o StrictHostKeyChecking=no -i "$AWS_PRIVATE_KEY" ubuntu@$AWS_IP "ls -l /tmp/*.jar"
    - echo "Déploiement réussi sur AWS !"
  only:
    - master
    - main