stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  tags:
    - pc-younes
  script:
    - mvn clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

job_test:
  stage: test
  tags:
    - pc-younes
  script:
    - mvn test
  # On autorise la suite si les tests passent
  dependencies:
    - job_build

job_deploy_to_aws:
  stage: deploy
  tags:
    - pc-younes
  script:
    - echo "Déploiement vers AWS avec workaround OpenSSL Legacy..."
    - mvn package -DskipTests
    
    # 1. On force le support des anciens formats RSA pour ton Linux
    - export OPENSSL_CONF=/etc/ssl/openssl.cnf
    # Si la commande au dessus ne suffit pas, on utilise cette option directement dans SSH
    
    - cp "$AWS_PRIVATE_KEY" ./temp_key.pem
    - chmod 600 ./temp_key.pem
    
    - echo "Tentative de transfert..."
    # 2. On utilise des options qui forcent SSH à accepter les vieux formats (SHA1 et RSA)
    - scp -o StrictHostKeyChecking=no -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -i ./temp_key.pem target/*.jar ubuntu@$AWS_IP:/tmp/
    
    # 3. Déplacement sur le serveur
    - ssh -o StrictHostKeyChecking=no -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -i ./temp_key.pem ubuntu@$AWS_IP "sudo mv /tmp/*.jar /var/lib/tomcat9/webapps/"
    - echo "Application déployée avec succès !"
  only:
    - master
    - main