name: CI/CD INPT Cloud-DevOps

on:
  push:
    branches: [ main, master ]

jobs:
  # Étape A : Analyse SonarCloud (Questions A.5, A.8, A.9)
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # L'option wait=true force GitHub à attendre le verdict de SonarCloud (Étape A.9)
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=younesbslh121_lab-java-pipeline -Dsonar.qualitygate.wait=true

  # Étape B : Docker (Questions B.1, B.2, B.6)
  docker-build:
    needs: sonarcloud # On ne construit l'image que si la qualité est validée
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' # Équivalent de "only" (Étape B.6)
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest
